export const FORM_DATA_INIT = {
  securityAnswer: '',
  securityQuestion: '',
  nationality: '',
  family: '',
  bloodType: '',
  nickname: '',
  birthday: '',
  sns: '',
  job: '',
  mbti: '',
  city: '',
  image: null,
  content: '',
};
